### ISSUE TITLE
how do I convert from CID v0 to CID v1? 

### ISSUE THREAD

**Issue by mthinh** [dwyl/dart_cid#6]
I'm new with CID, how do I convert from CID v0 to CID v1?

**Comment by nelsonic** [comment]
@LuchoTurtle definitely `continue` working on this and push up the `code` you already have on a branch/PR. 🧑‍💻 ⌛ 
But don't get sucked into a rabbit hole of re-writing code based on a question ... no matter how well intentioned.

For context: when I applied `priority-1` to this it was to answer the _question_ not write any code.
If the answer is: "We don't yet have that functionality" that's fine. We just need some sort of response.
We (`@dwyl`) aren't using `v1` in our `App` _yet_. 
So spending _days_ on this is not a good use of time at this stage.
If we needed it in order to ship our `App` then yes, we would pour _all_ our time into and even recruit [`@freitzzz`](https://github.com/freitzzz) to help! 
But as it stands, there are higher priority `App` features on the [`list`](https://github.com/orgs/dwyl/projects/15/views/1?filterQuery=assignee%3ALuchoTurtle) that you should focus on.

**Comment by LuchoTurtle** [comment]
@mthinh I've added a method to convert `v0` to `v1` in the latest update. Make sure you're using the version `1.0.0` to make use of it. 👌
